version: '3.3'

services:
  mongo-1:
    image: mongo:4.2
    container_name: mongo-1
    networks:
      - ddcc-net
    volumes:
      - 'openhim-mongo1:/data/db'
    command: ['--replSet', 'mongo-set', '--wiredTigerCacheSizeGB', '0.5']

  mongo-2:
    image: mongo:4.2
    container_name: mongo-2
    networks:
      - ddcc-net
    volumes:
      - 'openhim-mongo2:/data/db'
    command: ['--replSet', 'mongo-set', '--wiredTigerCacheSizeGB', '0.5']

  mongo-3:
    image: mongo:4.2
    container_name: mongo-3
    networks:
      - ddcc-net
    volumes:
      - 'openhim-mongo3:/data/db'
    command: ['--replSet', 'mongo-set', '--wiredTigerCacheSizeGB', '0.5']

volumes:
  openhim-mongo1:
  openhim-mongo2:
  openhim-mongo3:

networks:
  ddcc-net:
    external: false
    name: ddcc-net